package com.hanghub.app.core.network

import com.hanghub.app.core.Config
import com.hanghub.app.data.dto.MessageEnvelopeDto
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.json.put
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import okhttp3.WebSocket
import okhttp3.WebSocketListener
import java.util.concurrent.atomic.AtomicInteger

/** Realtime events surfaced to the app from the chat WebSocket. */
sealed interface WsEvent {
    /** A `chat:message` — a new live message or one delivered via join replay. */
    data class IncomingMessage(val message: MessageEnvelopeDto) : WsEvent

    /** Server confirmation that one of our sends was persisted. */
    data class MessageAck(
        val clientMessageId: String?,
        val messageId: String,
        val seq: Long,
    ) : WsEvent

    data class MessageDeleted(val roomId: String, val messageId: String) : WsEvent
    data class Typing(val roomId: String, val userId: String, val isTyping: Boolean) : WsEvent
    data class RoomJoined(val roomId: String) : WsEvent
    data class PlanUpdated(val chatId: String) : WsEvent
    data class Connection(val connected: Boolean) : WsEvent
}

/**
 * Single WebSocket connection to the backend chat server, speaking the
 * modern `chat:*` protocol (`chat:join` / `chat:message` / `chat:typing`,
 * with server-assigned `seq`, `clientMessageId` idempotency and message
 * replay). Connects with the JWT as a query param and auto-reconnects with
 * exponential backoff.
 *
 * `chat:message` sends are queued while the socket is down and flushed on
 * reconnect, so a message composed offline is not silently lost.
 */
class WebSocketManager(
    private val okHttpClient: OkHttpClient,
    private val tokenProvider: () -> String?,
) {

    private val json = Json { ignoreUnknownKeys = true; isLenient = true }
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    private val _events = MutableSharedFlow<WsEvent>(extraBufferCapacity = 128)
    val events: SharedFlow<WsEvent> = _events

    private var webSocket: WebSocket? = null
    private var reconnectJob: Job? = null
    private val reconnectAttempt = AtomicInteger(0)
    @Volatile private var intentionallyClosed = false

    /** `chat:message` frames composed while the socket was down. */
    private val outbox = ArrayDeque<String>()
    private val outboxLock = Any()

    fun connect() {
        val token = tokenProvider() ?: return
        intentionallyClosed = false
        reconnectJob?.cancel()
        webSocket?.cancel()

        val request = Request.Builder()
            .url("${Config.WS_URL}?token=$token")
            .build()
        webSocket = okHttpClient.newWebSocket(request, listener)
    }

    fun disconnect() {
        intentionallyClosed = true
        reconnectJob?.cancel()
        webSocket?.close(1000, null)
        webSocket = null
    }

    // ── Modern chat:* protocol — outbound ───────────────────────────────────

    /**
     * Join a chat room. [lastSeenSeq] asks the server to replay every message
     * after that sequence as `chat:message` events — closing any gap from
     * while the socket was disconnected.
     */
    fun joinRoom(roomId: String, lastSeenSeq: Long) {
        send(buildJsonObject {
            put("type", "chat:join")
            put("roomId", roomId)
            put("lastSeenSeq", lastSeenSeq)
        })
    }

    fun leaveRoom(roomId: String) {
        send(buildJsonObject {
            put("type", "chat:leave")
            put("roomId", roomId)
        })
    }

    /**
     * Send a chat message. [id] and [clientMessageId] are pre-generated by the
     * caller so the optimistic UI row can be reconciled with the server echo /
     * ack, and so a retry is idempotent. Queued if the socket is down.
     */
    fun sendChatMessage(
        roomId: String,
        messageType: String,
        payload: JsonObject,
        id: String,
        clientMessageId: String,
    ) {
        val frame = buildJsonObject {
            put("type", "chat:message")
            put("roomId", roomId)
            put("messageType", messageType)
            put("id", id)
            put("clientMessageId", clientMessageId)
            put("payload", payload)
        }.toString()

        if (!sendRaw(frame)) {
            synchronized(outboxLock) { outbox.addLast(frame) }
        }
    }

    fun sendTyping(roomId: String, isTyping: Boolean) {
        send(buildJsonObject {
            put("type", "chat:typing")
            put("roomId", roomId)
            put("isTyping", isTyping)
        })
    }

    private fun send(obj: JsonObject) {
        sendRaw(obj.toString())
    }

    /** Returns true if the frame was handed to an open socket. */
    private fun sendRaw(raw: String): Boolean = webSocket?.send(raw) ?: false

    private fun flushOutbox() {
        val pending: List<String>
        synchronized(outboxLock) {
            pending = outbox.toList()
            outbox.clear()
        }
        for (frame in pending) {
            if (!sendRaw(frame)) {
                synchronized(outboxLock) { outbox.addLast(frame) }
            }
        }
    }

    // ── Connection lifecycle ────────────────────────────────────────────────

    private val listener = object : WebSocketListener() {
        override fun onOpen(webSocket: WebSocket, response: Response) {
            reconnectAttempt.set(0)
            _events.tryEmit(WsEvent.Connection(true))
            flushOutbox()
        }

        override fun onMessage(webSocket: WebSocket, text: String) {
            handleIncoming(text)
        }

        override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
            _events.tryEmit(WsEvent.Connection(false))
            if (!intentionallyClosed) scheduleReconnect()
        }

        override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) {
            _events.tryEmit(WsEvent.Connection(false))
            if (!intentionallyClosed) scheduleReconnect()
        }
    }

    private fun scheduleReconnect() {
        reconnectJob?.cancel()
        val attempt = reconnectAttempt.getAndIncrement()
        val delaySecs = minOf(Math.pow(2.0, attempt.toDouble()), 30.0)
        reconnectJob = scope.launch {
            delay((delaySecs * 1000).toLong())
            if (!intentionallyClosed) connect()
        }
    }

    // ── Incoming ────────────────────────────────────────────────────────────

    private fun handleIncoming(text: String) {
        val obj = try {
            json.parseToJsonElement(text) as? JsonObject ?: return
        } catch (_: Exception) {
            return
        }
        when (obj.str("type")) {
            "chat:message" -> {
                val msgEl = obj["message"] ?: return
                val envelope = try {
                    json.decodeFromJsonElement(MessageEnvelopeDto.serializer(), msgEl)
                } catch (_: Exception) {
                    return
                }
                _events.tryEmit(WsEvent.IncomingMessage(envelope))
            }
            "chat:message_ack" -> {
                val messageId = obj.str("messageId") ?: return
                _events.tryEmit(
                    WsEvent.MessageAck(
                        clientMessageId = obj.str("clientMessageId"),
                        messageId = messageId,
                        seq = obj["seq"]?.jsonPrimitive?.longOrNull ?: 0,
                    )
                )
            }
            "chat:message_deleted" -> {
                val roomId = obj.str("roomId") ?: return
                val messageId = obj.str("messageId") ?: return
                _events.tryEmit(WsEvent.MessageDeleted(roomId, messageId))
            }
            "chat:typing" -> {
                val roomId = obj.str("roomId") ?: return
                val userId = obj.str("userId") ?: return
                _events.tryEmit(
                    WsEvent.Typing(
                        roomId = roomId,
                        userId = userId,
                        isTyping = obj["isTyping"]?.jsonPrimitive?.booleanOrNull ?: false,
                    )
                )
            }
            "chat:joined", "joined_chat" -> {
                val roomId = obj.str("roomId") ?: obj.str("chatId") ?: return
                _events.tryEmit(WsEvent.RoomJoined(roomId))
            }
            "plan_updated", "plan_state_changed", "plan_locked", "vote_cast", "rsvp_updated" -> {
                obj.str("chatId")?.let { _events.tryEmit(WsEvent.PlanUpdated(it)) }
            }
            // `message_sent` / `receive_message` / `typing` are the legacy
            // event names the same payload is also broadcast under for older
            // iOS clients — ignored here to avoid double-handling.
        }
    }

    private fun JsonObject.str(key: String): String? =
        this[key]?.jsonPrimitive?.contentOrNull
}
